version: 1.0.{build}
os: Visual Studio 2015

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set MAVEN_VERSION=3.2.5
  - choco install maven -version %MAVEN_VERSION%
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin
  - set JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0

environment:
  MSBUILD_PATH: C:\PROGRA~2\MSBuild\14.0\Bin\MSBuild.exe
  MSTEST_PATH: C:\PROGRA~2\MICROS~3.0\Common7\IDE\MSTest.exe

build_script:
  - mvn clean install

test: off

notifications:
- provider: HipChat
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
