version: 1.0.{build}
os: Visual Studio 2015

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set MAVEN_VERSION=3.6.1
  - choco install maven -version %MAVEN_VERSION%
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin

environment:
  MSBUILD_PATH: C:\PROGRA~2\MSBuild\14.0\Bin\MSBuild.exe

build_script:
  - mvn clean install "--batch-mode"

test: off
