version: 1.0.{build}
image: Visual Studio 2019

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set MAVEN_VERSION=3.6.1
  - choco install maven -version %MAVEN_VERSION%
  - refreshenv
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin

environment:
  MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe

before_build:
  - nuget restore

build_script:
  - mvn clean install "--batch-mode"

test: off
