version: 1.0.{build}
os: Visual Studio 2015

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set MAVEN_VERSION=3.6.1
  - choco install maven -version %MAVEN_VERSION%
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin

environment:
  MSBUILD_PATH: C:\PROGRA~2\MSBuild\14.0\Bin\MSBuild.exe

build_script:
  - mvn clean package --batch-mode
  - ps: if ($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH) { $env:APPVEYOR_REPO_BRANCH = $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH; }
  - mvn sonar:sonar -Dsonar.projectKey=lg2de_sonar-scm-tfvc -Dsonar.organization=lg2de -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=bc95cf028203c4093dc26fcf45cc0563315ee582 -Dsonar.branch.name=%APPVEYOR_REPO_BRANCH%

test: off

artifacts:
- path: sonar-scm-tfvc-plugin/target/*.jar
  name: plugin
